### ISSUE TITLE
Does this work on cross compiltion ?

### ISSUE THREAD

**Issue by serak** [power-devops/perfstat#4]
i am getting this error while trying

# perstat
.\main.go:11:19: undefined: perfstat.CpuTotalStat
.\main.go:24:22: undefined: perfstat.CpuStat
.\main.go:34:22: undefined: perfstat.CpuUtilStat

**Comment by aklyachkin** [comment]
No, it doesn't. It requires cgo and IBM AIX libperfstat, which is not available on other platforms.
